# netlify.toml — Next.js + Prisma (serverless) clean config

[build]
  command = "npm run build"
  publish = ".next"

# Use the official Next.js plugin so SSR, /api/* and routing work
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Bundle Prisma engines into serverless functions
[functions]
  included_files = [
    "node_modules/.prisma/**",
    "node_modules/@prisma/client/**"
  ]

# Optional but recommended: set Node version (18+)
[build.environment]
  NODE_VERSION = "18"

# ⚠️ DO NOT add a catch-all redirect to /index.html for Next.js apps.
# It breaks /api/* and SSR/ISR routes. The Next plugin handles routing.
