[build]
  publish = ".next"
  command = "npm run build"

[functions]
  directory = ".next/server"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"