[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  API_BASE_URL = "https://milestone-api-production.up.railway.app"
  NEXT_PUBLIC_API_BASE_URL = "https://milestone-api-production.up.railway.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"
