[build]
  command = "rm -rf pages/api/ && cp package.netlify.json package.json && npm install && npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.20.0"