[build]
  publish = ".next"
  command = "npm run build"

# CRITICAL: This enables SSR like localhost
[functions]
  directory = ".next/server"
  node_bundler = "esbuild"

# Optional: If you want to use API routes on Netlify
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
